export const APP_NAME = 'PayFlow';
export const APP_TAGLINE = 'Comprenez votre salaire instantanément';

export const LABELS = {
  grossMonthly: 'Brut mensuel',
  netMonthly: 'Net mensuel',
  gross: 'Brut',
  net: 'Net',
  monthly: 'Mois',
  yearly: 'An',
  daily: 'Jour',
  monthlyFull: 'mensuel',
  yearlyFull: 'annuel',
  dailyFull: 'journalier',
  history: 'Historique',
  save: 'Sauvegarder',
  share: 'Partager',
  copy: 'Copier',
  close: 'Fermer',
  details: 'Voir le détail',
  quickMode: 'Mode rapide',
  compare: 'Comparer',
  target: 'Objectif',
  settings: 'Réglages',
  result: 'Résultat',
  reset: 'Réinitialiser',
  delete: 'Supprimer',
  cancel: 'Annuler',
  apply: 'Appliquer',
  skip: 'Passer',
  continue: 'Continuer',
  shareResults: 'Partager les résultats',
  generatedWith: `Calculé avec ${APP_NAME}`,
  emptyHistory: 'Aucune simulation',
  emptyHistoryMsg: 'Saisissez un montant et sauvegardez votre première simulation.',
  emptyCompare: 'Comparer les salaires',
  emptyCompareMsg: 'Saisissez un montant brut pour comparer entre deux pays.',
  emptyTarget: 'Définir un objectif',
  emptyTargetMsg: 'Entrez le salaire net souhaité pour voir les calculs.',
} as const;
