export const APP_NAME = 'PayFlow';
export const APP_TAGLINE = 'Salary Calculator';

export const LABELS = {
  grossMonthly: 'Brut mensuel',
  netMonthly: 'Net mensuel',
  gross: 'Brut',
  net: 'Net',
  monthly: 'Mois',
  yearly: 'An',
  daily: 'Jour',
  monthlyFull: 'mensuel',
  yearlyFull: 'annuel',
  dailyFull: 'journalier',
  history: 'Historique',
  save: 'Sauvegarder',
  share: 'Partager',
  copy: 'Copier',
  close: 'Fermer',
  details: 'Voir le détail',
  quickMode: 'Mode rapide',
  compare: 'Comparer',
  target: 'Objectif',
  settings: 'Réglages',
  result: 'Résultat',
  simulation: 'Résultat',
  reset: 'Réinitialiser',
  delete: 'Supprimer',
  cancel: 'Annuler',
  apply: 'Appliquer',
  skip: 'Passer',
  continue: 'Continuer',
  shareResults: 'Partager les résultats',
  generatedWith: `Calculé avec ${APP_NAME}`,
} as const;
